<?php

/**
 * @file
 *  Tried using hook_hosting_tasks() to extend platform tasks but couldn't
 *  get it to work. No time to dig in the code.
 */

/**
 * Implementation of hook_menu().
 */
function platform_delete_sites_menu() {
  return array(
    'node/%node/disable_sites' => array(
      'title'                   => 'No turning back...',
      'page callback'           => 'platform_delete_sites_execute_disable',
      'page arguments'          => array(1),
      'access arguments'        => array('administer nodes'),
    ),
    'node/%node/delete_sites' => array(
      'title'                   => 'No turning back...',
      'page callback'           => 'platform_delete_sites_execute_delete',
      'page arguments'          => array(1),
      'access arguments'        => array('administer nodes'),
    ),
    'node/%node/delete_hard' => array(
      'title'                   => 'No turning back...',
      'page callback'           => 'platform_delete_sites_execute_delete_hard',
      'page arguments'          => array(1),
      'access arguments'        => array('administer nodes'),
    ),
  );
}

/**
 * Spawn disable tasks for all sites on selected platform
 */
function platform_delete_sites_execute_disable($node) {
  // Get all non disabled sites and spawn disable tasks for all of them
  $enabled_sites = db_query("SELECT nid FROM {hosting_site}
    WHERE platform = %d AND status = 1", array(':platform' => $node->nid));
  while ($site = db_fetch_object($enabled_sites)) {
    hosting_add_task($site->nid, 'disable');
  }

  drupal_goto('<front>');
}

/**
 * Spawn disable tasks for all sites on selected platform
 */
function platform_delete_sites_execute_delete($node) {
  // Get all disabled sites and spawn delete tasks for all of them
  $enabled_sites = db_query("SELECT nid FROM {hosting_site}
    WHERE platform = %d AND status = 0", array(':platform' => $node->nid));
  while ($site = db_fetch_object($enabled_sites)) {
    hosting_add_task($site->nid, 'delete');
  }

  drupal_goto('<front>');
}

/**
 * Delete all sites the ugly way
 */
function platform_delete_sites_execute_delete_hard($platform) {
  return confirm_form(
      array('#node' => $platform),
      'Delete all sites?',
      '<front>',
      'Cannot be undone. EVVAH!',
      'Do it!',
      'Cancel'
    );
}

function platform_delete_sites_execute_delete_hard_submit($form, $form_state) {
  $platform = $form['#node'];

  $batch = array(
    'title'             => 'Deleting a crap load of sites',
    'operations'        => array(),
    'finished'          => 'platform_delete_sites_execute',
    'init_message'      => 'Warming up the engines',
    'progress_message'  => 'Deleted @current of @total sites.',
    'error_message'     => 'Ooops.. :/',
  );

  $sites = db_query("SELECT nid FROM {hosting_site}
    WHERE platform = %d", array(':platform' => $platform->nid));

  while ($site = db_fetch_object($sites)) {
    $batch['operations'][] = array('platform_delete_sites_site', array($site->nid));
  }

  // Tip the first domino.
  batch_set($batch);
}

function platform_delete_sites_site($nid) {
  node_delete($nid);
}